# Generated by Django 3.1.1 on 2020-09-17 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('title', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('url', models.CharField(blank=True, max_length=200)),
                ('etymology', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('synonym_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.word')),
            ],
        ),
    ]
