# Generated by Django 3.1.1 on 2020-09-17 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_definition_example_synonym_relation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='definition',
            old_name='defintion',
            new_name='definition',
        ),
    ]
