# Generated by Django 3.1.1 on 2020-09-18 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200917_2105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='synonym_from',
        ),
        migrations.AlterField(
            model_name='definition',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='definitions', to='api.word'),
        ),
        migrations.AlterField(
            model_name='example',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examples', to='api.word'),
        ),
        migrations.AlterField(
            model_name='synonym_relation',
            name='word_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='synonyms', to='api.word'),
        ),
    ]
