# Generated by Django 3.1.1 on 2020-09-18 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200918_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='definition',
            name='syntax',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
