# Generated by Django 3.1.1 on 2020-10-18 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200918_2131'),
    ]

    operations = [
        migrations.RenameField(
            model_name='word',
            old_name='title',
            new_name='w_id',
        ),
        migrations.AddField(
            model_name='word',
            name='word',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
